### PR TITLE
Promisify bin/chewbacca.js

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by papandreou** [comment]
Oh, didn't realize that you already have the rsvp library in there. Are you using that to avoid being affected by Unexpected's monkey-patching of bluebird?

**Comment by sunesimonsen** [comment]
Hmm I don't, probably though it was more light weight. But now that we do our own timing it doesn't matter.

**Comment by sunesimonsen** [comment]
This branch needs to be rebased on master - sorry.

**Comment by papandreou** [comment]
Done

**Pull request merged**
